### ISSUE TITLE
Vue - TODO

### ISSUE THREAD

**Issue by thruthesky** [thruthesky/cms#72]
- [x] Phone Number verification.
- [x] Push notification for all users.
- [ ] Push notification for forum.
  - [x] User can enable/disable push notification for each forum. Default off for all forum.
  - [x] User can enable/disable to receive push notification when somebody reply on my post/comment. Default is on.
